"""
Sections Generator for PDF Reports
Generates content for each report section
"""
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

from .tables import TableGenerator


class SectionGenerator:
    """Generates content for PDF report sections"""
    
    def __init__(self, context: Dict[str, Any]):
        """
        Initialize section generator
        
        Args:
            context: Complete pipeline context
        """
        self.context = context
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Check if styles exist by trying to access them
        try:
            self.styles['Heading1']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading1',
                parent=self.styles['Heading1'],
                fontSize=20,
                textColor=colors.darkblue,
                spaceAfter=20
            ))
        
        try:
            self.styles['Heading2']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading2',
                parent=self.styles['Heading2'],
                fontSize=16,
                textColor=colors.darkblue,
                spaceAfter=12
            ))
        
        try:
            self.styles['Heading3']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading3',
                parent=self.styles['Heading3'],
                fontSize=14,
                textColor=colors.darkblue,
                spaceAfter=10
            ))
        
        try:
            self.styles['BodyText']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='BodyText',
                parent=self.styles['Normal'],
                fontSize=10,
                leading=14,
                spaceAfter=8
            ))
    
    def get_cover_page(self) -> List:
        """Generate cover page content"""
        elements = []
        
        # Title
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph(
            "AI Data Intelligence Report",
            self.styles['Title']
        ))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Subtitle
        elements.append(Paragraph(
            "Comprehensive Data Analysis & Machine Learning Report",
            self.styles['Heading2']
        ))
        elements.append(Spacer(1, 0.5 * inch))
        
        # Dataset name
        dataset = self.context.get('dataset', {})
        elements.append(Paragraph(
            f"<b>Dataset:</b> {dataset.get('file_name', 'Unknown')}",
            self.styles['Normal']
        ))
        
        # Date
        elements.append(Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}",
            self.styles['Normal']
        ))
        
        # Version
        elements.append(Paragraph(
            "<b>Version:</b> 1.0",
            self.styles['Normal']
        ))
        
        # Footer
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph(
            "Generated by AI Data Intelligence Platform",
            self.styles['Normal']
        ))
        
        return elements
    
    def get_dataset_overview(self) -> List:
        """Generate dataset overview section"""
        elements = []
        
        elements.append(Paragraph("Dataset Overview", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        table = TableGenerator.create_dataset_overview_table(dataset)
        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))
        
        return elements
    
    def get_quality_section(self) -> List:
        """Generate data quality section"""
        elements = []
        
        elements.append(Paragraph("Data Quality Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        validation = self.context.get('validation', {})
        quality = validation.get('quality', {})
        
        # Quality table
        table = TableGenerator.create_quality_table(quality)
        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))
        
        # Warnings
        warnings = quality.get('warnings', [])
        if warnings:
            elements.append(Paragraph("Warnings:", self.styles['Heading3']))
            for warning in warnings[:5]:
                elements.append(Paragraph(f"• {warning}", self.styles['Normal']))
        
        return elements
    
    def get_missing_values_section(self) -> List:
        """Generate missing values section"""
        elements = []
        
        elements.append(Paragraph("Missing Values Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        missing = dataset.get('missing_values', {})
        
        table = TableGenerator.create_missing_values_table(missing)
        elements.append(table)
        
        return elements
    
    def get_outlier_section(self) -> List:
        """Generate outlier analysis section"""
        elements = []
        
        elements.append(Paragraph("Outlier Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        outliers = self.context.get('outliers', {})
        table = TableGenerator.create_outlier_table(outliers)
        elements.append(table)
        
        return elements
    
    def get_eda_section(self) -> List:
        """Generate EDA section"""
        elements = []
        
        elements.append(Paragraph("Exploratory Data Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        eda = self.context.get('eda', {})
        insights = eda.get('insights', {}).get('insights', [])
        
        if insights:
            for insight in insights[:5]:
                elements.append(Paragraph(f"• {insight}", self.styles['Normal']))
        else:
            elements.append(Paragraph("No EDA insights available.", self.styles['Normal']))
        
        return elements
    
    def get_feature_engineering_section(self) -> List:
        """Generate feature engineering section"""
        elements = []
        
        elements.append(Paragraph("Feature Engineering", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        feature_eng = self.context.get('feature_engineering', {})
        
        # Feature roles
        roles = feature_eng.get('feature_roles', {})
        if roles:
            elements.append(Paragraph("Feature Roles:", self.styles['Heading3']))
            for col, role in list(roles.items())[:10]:
                elements.append(Paragraph(f"• {col}: {role}", self.styles['Normal']))
        
        return elements
    
    def get_automl_section(self) -> List:
        """Generate AutoML section"""
        elements = []
        
        elements.append(Paragraph("AutoML Results", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        automl = self.context.get('automl', {})
        
        # Best model
        best = automl.get('best_model', {})
        if best:
            elements.append(Paragraph(
                f"<b>Best Model:</b> {best.get('name', 'Unknown')}",
                self.styles['Normal']
            ))
            elements.append(Paragraph(
                f"<b>Score:</b> {best.get('score', 0):.3f}",
                self.styles['Normal']
            ))
            elements.append(Paragraph(
                f"<b>Reason:</b> {best.get('reason', 'N/A')}",
                self.styles['Normal']
            ))
            elements.append(Spacer(1, 0.2 * inch))
        
        # Model comparison
        ranked = automl.get('ranked_models', [])
        if ranked:
            table = TableGenerator.create_model_comparison_table(ranked)
            elements.append(table)
        
        return elements
    
    def get_explainability_section(self) -> List:
        """Generate explainability section"""
        elements = []
        
        elements.append(Paragraph("Model Explainability", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        explainability = self.context.get('explainability', {})
        
        # Feature importance
        ranking = explainability.get('feature_ranking', [])
        if ranking:
            table = TableGenerator.create_feature_importance_table(ranking)
            elements.append(table)
        
        # Global explanation
        global_exp = explainability.get('global_explanation', {})
        summary = global_exp.get('summary', [])
        if summary:
            elements.append(Paragraph("Global Explanation:", self.styles['Heading3']))
            for s in summary:
                elements.append(Paragraph(f"• {s}", self.styles['Normal']))
        
        return elements
    
    def get_insights_section(self) -> List:
        """Generate AI insights section"""
        elements = []
        
        elements.append(Paragraph("Business Insights", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        insights = self.context.get('insights', {})
        
        # Executive summary
        summary = insights.get('executive_summary', '')
        if summary:
            elements.append(Paragraph("Executive Summary:", self.styles['Heading3']))
            elements.append(Paragraph(summary, self.styles['Normal']))
            elements.append(Spacer(1, 0.2 * inch))
        
        # Recommendations
        recommendations = insights.get('recommendations', [])
        if recommendations:
            table = TableGenerator.create_recommendations_table(recommendations)
            elements.append(table)
            elements.append(Spacer(1, 0.2 * inch))
        
        # Next steps
        next_steps = insights.get('next_steps', [])
        if next_steps:
            elements.append(Paragraph("Next Steps:", self.styles['Heading3']))
            for step in next_steps:
                elements.append(Paragraph(f"• {step}", self.styles['Normal']))
        
        # AI Health Score
        health = insights.get('ai_health_score', {})
        if health:
            elements.append(Paragraph(
                f"<b>AI Health Score:</b> {health.get('score', 0)}/100 "
                f"({health.get('confidence', 'Unknown')} Confidence)",
                self.styles['Normal']
            ))
        
        return elements
    
    def get_appendix(self) -> List:
        """Generate appendix section"""
        elements = []
        
        elements.append(Paragraph("Appendix", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Pipeline metadata
        elements.append(Paragraph("Pipeline Information:", self.styles['Heading3']))
        elements.append(Paragraph(
            f"<b>Pipeline Version:</b> 1.0",
            self.styles['Normal']
        ))
        elements.append(Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            self.styles['Normal']
        ))
        
        # Dataset columns
        dataset = self.context.get('dataset', {})
        columns = dataset.get('columns', [])
        if columns:
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("Dataset Columns:", self.styles['Heading3']))
            for col in columns:
                elements.append(Paragraph(f"• {col}", self.styles['Normal']))
        
        return elements
