"""
Sections Generator for PDF Reports
"""
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

from .tables import TableGenerator


class SectionGenerator:
    def __init__(self, context: Dict[str, Any]):
        self.context = context
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        try:
            self.styles['Heading1']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading1',
                parent=self.styles['Heading1'],
                fontSize=20,
                textColor=colors.darkblue,
                spaceAfter=20
            ))
        try:
            self.styles['Heading2']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading2',
                parent=self.styles['Heading2'],
                fontSize=16,
                textColor=colors.darkblue,
                spaceAfter=12
            ))
        try:
            self.styles['BodyText']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='BodyText',
                parent=self.styles['Normal'],
                fontSize=10,
                leading=14,
                spaceAfter=8
            ))
    
    def get_cover_page(self) -> List:
        elements = []
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("AI Data Intelligence Report", self.styles['Title']))
        elements.append(Spacer(1, 0.3 * inch))
        elements.append(Paragraph("Comprehensive Data Analysis Report", self.styles['Heading2']))
        elements.append(Spacer(1, 0.5 * inch))
        
        dataset = self.context.get('dataset', {})
        elements.append(Paragraph(f"<b>Dataset:</b> {dataset.get('file_name', 'Unknown')}", self.styles['Normal']))
        elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}", self.styles['Normal']))
        elements.append(Paragraph("<b>Version:</b> 1.0", self.styles['Normal']))
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("Generated by AI Data Intelligence Platform", self.styles['Normal']))
        return elements
    
    def get_dataset_overview(self) -> List:
        elements = []
        elements.append(Paragraph("Dataset Overview", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        shape = dataset.get('shape', {})
        
        data = [
            ['Property', 'Value'],
            ['Rows', str(shape.get('rows', 0))],
            ['Columns', str(shape.get('columns', 0))],
            ['Numeric Columns', str(len(dataset.get('numeric_columns', [])))],
            ['Categorical Columns', str(len(dataset.get('categorical_columns', [])))],
            ['File Name', dataset.get('file_name', 'Unknown')]
        ]
        table = TableGenerator._create_table(data, "Dataset Overview")
        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))
        return elements
    
    def get_quality_section(self) -> List:
        elements = []
        elements.append(Paragraph("Data Quality Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        validation = self.context.get('validation', {})
        quality = validation.get('quality', {})
        score = quality.get('quality_score', 0)
        
        data = [
            ['Metric', 'Value', 'Status'],
            ['Quality Score', f"{score}/100", '✅ Good' if score >= 70 else '⚠️ Needs Improvement'],
            ['Warnings', str(quality.get('total_warnings', 0)), '⚠️ Review Required' if quality.get('total_warnings', 0) > 0 else '✅ None']
        ]
        table = TableGenerator._create_table(data, "Quality Metrics")
        elements.append(table)
        
        warnings = quality.get('warnings', [])
        if warnings:
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("Warnings:", self.styles['Heading3']))
            for warning in warnings[:5]:
                elements.append(Paragraph(f"• {warning}", self.styles['Normal']))
        
        return elements
    
    def get_missing_values_section(self) -> List:
        elements = []
        elements.append(Paragraph("Missing Values Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        missing = dataset.get('missing_values', {})
        
        data = [['Column', 'Missing Values', 'Percentage']]
        has_missing = False
        for col, count in missing.items():
            if count > 0:
                has_missing = True
                total = len(missing)
                pct = (count / sum(missing.values()) * 100) if sum(missing.values()) > 0 else 0
                data.append([col, str(count), f"{pct:.1f}%"])
        
        if not has_missing:
            data.append(['No missing values found', '', ''])
        
        table = TableGenerator._create_table(data, "Missing Values")
        elements.append(table)
        return elements
    
    def get_outlier_section(self) -> List:
        elements = []
        elements.append(Paragraph("Outlier Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        outliers = self.context.get('outliers', {})
        summary = outliers.get('summary', {})
        
        if not summary.get('has_numeric_data', True):
            elements.append(Paragraph("No numeric columns found for outlier analysis.", self.styles['Normal']))
            return elements
        
        data = [['Column', 'Outliers', 'Percentage', 'Severity']]
        has_outliers = False
        
        analysis = outliers.get('analysis', {})
        for col, info in analysis.items():
            if isinstance(info, dict) and 'outlier_analysis' in info:
                outlier_data = info.get('outlier_analysis', {})
                count = outlier_data.get('outlier_count', 0)
                pct = outlier_data.get('outlier_percentage', 0)
                severity = info.get('severity', 'None')
                
                if count > 0:
                    has_outliers = True
                    data.append([col, str(count), f"{pct:.1f}%", severity])
        
        if not has_outliers:
            data.append(['No outliers detected', '', '', ''])
        
        table = TableGenerator._create_table(data, "Outlier Analysis")
        elements.append(table)
        return elements
    
    def get_eda_section(self) -> List:
        elements = []
        elements.append(Paragraph("Exploratory Data Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        eda = self.context.get('eda', {})
        insights = eda.get('insights', {}).get('insights', [])
        
        if insights:
            for insight in insights[:5]:
                elements.append(Paragraph(f"• {insight}", self.styles['Normal']))
        else:
            elements.append(Paragraph("No EDA insights available.", self.styles['Normal']))
        
        return elements
    
    def get_feature_engineering_section(self) -> List:
        elements = []
        elements.append(Paragraph("Feature Engineering", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        feature_eng = self.context.get('feature_engineering', {})
        roles = feature_eng.get('feature_roles', {})
        
        if roles:
            for col, role in list(roles.items())[:10]:
                elements.append(Paragraph(f"• {col}: {role}", self.styles['Normal']))
        else:
            elements.append(Paragraph("No feature engineering data available.", self.styles['Normal']))
        
        return elements
    
    def get_automl_section(self) -> List:
        elements = []
        elements.append(Paragraph("AutoML Results", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        automl = self.context.get('automl', {})
        best = automl.get('best_model', {})
        
        if best:
            elements.append(Paragraph(f"<b>Bestcat > /Users/raghuviranturkar/AI-Data-Intelligence/backend/app/services/reports/sections.py << 'EOF'
"""
Sections Generator for PDF Reports
"""
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

from .tables import TableGenerator


class SectionGenerator:
    def __init__(self, context: Dict[str, Any]):
        self.context = context
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        try:
            self.styles['Heading1']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading1',
                parent=self.styles['Heading1'],
                fontSize=20,
                textColor=colors.darkblue,
                spaceAfter=20
            ))
        try:
            self.styles['Heading2']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='Heading2',
                parent=self.styles['Heading2'],
                fontSize=16,
                textColor=colors.darkblue,
                spaceAfter=12
            ))
        try:
            self.styles['BodyText']
        except KeyError:
            self.styles.add(ParagraphStyle(
                name='BodyText',
                parent=self.styles['Normal'],
                fontSize=10,
                leading=14,
                spaceAfter=8
            ))
    
    def get_cover_page(self) -> List:
        elements = []
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("AI Data Intelligence Report", self.styles['Title']))
        elements.append(Spacer(1, 0.3 * inch))
        elements.append(Paragraph("Comprehensive Data Analysis Report", self.styles['Heading2']))
        elements.append(Spacer(1, 0.5 * inch))
        
        dataset = self.context.get('dataset', {})
        elements.append(Paragraph(f"<b>Dataset:</b> {dataset.get('file_name', 'Unknown')}", self.styles['Normal']))
        elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}", self.styles['Normal']))
        elements.append(Paragraph("<b>Version:</b> 1.0", self.styles['Normal']))
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("Generated by AI Data Intelligence Platform", self.styles['Normal']))
        return elements
    
    def get_dataset_overview(self) -> List:
        elements = []
        elements.append(Paragraph("Dataset Overview", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        shape = dataset.get('shape', {})
        
        data = [
            ['Property', 'Value'],
            ['Rows', str(shape.get('rows', 0))],
            ['Columns', str(shape.get('columns', 0))],
            ['Numeric Columns', str(len(dataset.get('numeric_columns', [])))],
            ['Categorical Columns', str(len(dataset.get('categorical_columns', [])))],
            ['File Name', dataset.get('file_name', 'Unknown')]
        ]
        table = TableGenerator._create_table(data, "Dataset Overview")
        elements.append(table)
        elements.append(Spacer(1, 0.3 * inch))
        return elements
    
    def get_quality_section(self) -> List:
        elements = []
        elements.append(Paragraph("Data Quality Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        validation = self.context.get('validation', {})
        quality = validation.get('quality', {})
        score = quality.get('quality_score', 0)
        
        data = [
            ['Metric', 'Value', 'Status'],
            ['Quality Score', f"{score}/100", '✅ Good' if score >= 70 else '⚠️ Needs Improvement'],
            ['Warnings', str(quality.get('total_warnings', 0)), '⚠️ Review Required' if quality.get('total_warnings', 0) > 0 else '✅ None']
        ]
        table = TableGenerator._create_table(data, "Quality Metrics")
        elements.append(table)
        
        warnings = quality.get('warnings', [])
        if warnings:
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("Warnings:", self.styles['Heading3']))
            for warning in warnings[:5]:
                elements.append(Paragraph(f"• {warning}", self.styles['Normal']))
        
        return elements
    
    def get_missing_values_section(self) -> List:
        elements = []
        elements.append(Paragraph("Missing Values Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        dataset = self.context.get('dataset', {})
        missing = dataset.get('missing_values', {})
        
        data = [['Column', 'Missing Values', 'Percentage']]
        has_missing = False
        for col, count in missing.items():
            if count > 0:
                has_missing = True
                total = len(missing)
                pct = (count / sum(missing.values()) * 100) if sum(missing.values()) > 0 else 0
                data.append([col, str(count), f"{pct:.1f}%"])
        
        if not has_missing:
            data.append(['No missing values found', '', ''])
        
        table = TableGenerator._create_table(data, "Missing Values")
        elements.append(table)
        return elements
    
    def get_outlier_section(self) -> List:
        elements = []
        elements.append(Paragraph("Outlier Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        outliers = self.context.get('outliers', {})
        summary = outliers.get('summary', {})
        
        if not summary.get('has_numeric_data', True):
            elements.append(Paragraph("No numeric columns found for outlier analysis.", self.styles['Normal']))
            return elements
        
        data = [['Column', 'Outliers', 'Percentage', 'Severity']]
        has_outliers = False
        
        analysis = outliers.get('analysis', {})
        for col, info in analysis.items():
            if isinstance(info, dict) and 'outlier_analysis' in info:
                outlier_data = info.get('outlier_analysis', {})
                count = outlier_data.get('outlier_count', 0)
                pct = outlier_data.get('outlier_percentage', 0)
                severity = info.get('severity', 'None')
                
                if count > 0:
                    has_outliers = True
                    data.append([col, str(count), f"{pct:.1f}%", severity])
        
        if not has_outliers:
            data.append(['No outliers detected', '', '', ''])
        
        table = TableGenerator._create_table(data, "Outlier Analysis")
        elements.append(table)
        return elements
    
    def get_eda_section(self) -> List:
        elements = []
        elements.append(Paragraph("Exploratory Data Analysis", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        eda = self.context.get('eda', {})
        insights = eda.get('insights', {}).get('insights', [])
        
        if insights:
            for insight in insights[:5]:
                elements.append(Paragraph(f"• {insight}", self.styles['Normal']))
        else:
            elements.append(Paragraph("No EDA insights available.", self.styles['Normal']))
        
        return elements
    
    def get_feature_engineering_section(self) -> List:
        elements = []
        elements.append(Paragraph("Feature Engineering", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        feature_eng = self.context.get('feature_engineering', {})
        roles = feature_eng.get('feature_roles', {})
        
        if roles:
            for col, role in list(roles.items())[:10]:
                elements.append(Paragraph(f"• {col}: {role}", self.styles['Normal']))
        else:
            elements.append(Paragraph("No feature engineering data available.", self.styles['Normal']))
        
        return elements
    
    def get_automl_section(self) -> List:
        elements = []
        elements.append(Paragraph("AutoML Results", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        automl = self.context.get('automl', {})
        best = automl.get('best_model', {})
        
        if best:
            elements.append(Paragraph(f"<b>Best Model:</b> {best.get('name', 'Unknown')}", self.styles['Normal']))
            elements.append(Paragraph(f"<b>Score:</b> {best.get('score', 0):.3f}", self.styles['Normal']))
            elements.append(Spacer(1, 0.2 * inch))
        else:
            elements.append(Paragraph("No AutoML results available.", self.styles['Normal']))
        
        ranked = automl.get('ranked_models', [])
        if ranked:
            data = [['Rank', 'Model', 'Score', 'CV Score']]
            for model in ranked[:5]:
                data.append([
                    str(model.get('rank', '')),
                    model.get('model_name', 'Unknown'),
                    f"{model.get('score', 0):.3f}",
                    f"{model.get('cv_score', 0):.3f}"
                ])
            table = TableGenerator._create_table(data, "Model Performance")
            elements.append(table)
        
        return elements
    
    def get_explainability_section(self) -> List:
        elements = []
        elements.append(Paragraph("Model Explainability", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        explainability = self.context.get('explainability', {})
        ranking = explainability.get('feature_ranking', [])
        
        if ranking:
            data = [['Rank', 'Feature', 'Importance', 'Impact']]
            for item in ranking[:10]:
                impact = 'High' if item.get('percentage', 0) > 10 else 'Medium' if item.get('percentage', 0) > 5 else 'Low'
                data.append([
                    str(item.get('rank', '')),
                    item.get('feature', 'Unknown'),
                    f"{item.get('importance', 0):.3f}",
                    impact
                ])
            table = TableGenerator._create_table(data, "Feature Importance")
            elements.append(table)
        else:
            elements.append(Paragraph("No explainability data available.", self.styles['Normal']))
        
        return elements
    
    def get_insights_section(self) -> List:
        elements = []
        elements.append(Paragraph("Business Insights", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        insights = self.context.get('insights', {})
        
        summary = insights.get('executive_summary', '')
        if summary:
            elements.append(Paragraph("Executive Summary:", self.styles['Heading3']))
            elements.append(Paragraph(summary, self.styles['Normal']))
            elements.append(Spacer(1, 0.2 * inch))
        
        recommendations = insights.get('recommendations', [])
        if recommendations:
            data = [['#', 'Recommendation']]
            for i, rec in enumerate(recommendations[:5], 1):
                data.append([str(i), rec])
            table = TableGenerator._create_table(data, "Key Recommendations")
            elements.append(table)
        
        health = insights.get('ai_health_score', {})
        if health:
            elements.append(Paragraph(
                f"<b>AI Health Score:</b> {health.get('score', 0)}/100 ({health.get('confidence', 'Unknown')} Confidence)",
                self.styles['Normal']
            ))
        
        return elements
    
    def get_appendix(self) -> List:
        elements = []
        elements.append(Paragraph("Appendix", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2 * inch))
        
        elements.append(Paragraph("Pipeline Information:", self.styles['Heading3']))
        elements.append(Paragraph(f"<b>Pipeline Version:</b> 1.0", self.styles['Normal']))
        elements.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.styles['Normal']))
        
        dataset = self.context.get('dataset', {})
        columns = dataset.get('columns', [])
        if columns:
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("Dataset Columns:", self.styles['Heading3']))
            for col in columns[:20]:
                elements.append(Paragraph(f"• {col}", self.styles['Normal']))
        
        return elements
